define([], function () {
  var free = {
    title: "Free Explore",
    key: "free",
    message: "Test out 'commit', 'branch', and 'checkout'",
    commitData: [{ id: "abc1234", tags: ["main"], message: "first commit" }],
  };

  var freeWithRemote = {
    title: "Free Explore with Remote",
    key: "free-remote",
    message: "Have fun!",
    commitData: [
      { id: "abc1234", tags: ["main", "origin/main"], message: "first commit" },
    ],
    originData: [{ id: "abc1234", tags: ["main"], message: "first commit" }],
  };

  var mergeExample = {
    title: "Merge Example",
    key: "merge-example",
    message: "Try merging `feature-1` or `feature-2` into `main`.",
    commitData: [
      {
        id: "abc1234",
        tags: [],
        message: "first commit",
        parent: "initial",
        cx: 50,
        cy: 369,
        branchless: false,
      },
      {
        id: "818b21c",
        tags: ["main", "HEAD"],
        parent: "abc1234",
        cx: 140,
        cy: 369,
        branchless: false,
      },
      {
        id: "5fb6bcc",
        tags: [],
        parent: "818b21c",
        cx: 230,
        cy: 369,
        branchless: false,
      },
      {
        id: "dcfc607",
        tags: ["feature-1"],
        parent: "5fb6bcc",
        cx: 320,
        cy: 369,
        branchless: false,
      },
      {
        id: "15ec1bd",
        tags: [],
        parent: "abc1234",
        cx: 140,
        cy: 279,
        branchless: false,
      },
      {
        id: "0f2baaf",
        tags: [],
        parent: "15ec1bd",
        cx: 230,
        cy: 279,
        branchless: false,
      },
      {
        id: "b1ecc95",
        tags: ["feature-2"],
        parent: "0f2baaf",
        cx: 320,
        cy: 279,
        branchless: false,
      },
    ],
    currentBranch: "main",
  };

  var rewrittenHistory = {
    title: "Rewritten Remote History",
    key: "rewritten-history",
    message: "Someone force-pushed and re-wrote history on the remote!",
    currentBranch: "feature",
    commitData: [
      {
        id: "abc1234",
        tags: [],
        message: "first commit",
        parent: "initial",
        cx: 50,
        cy: 437,
        branchless: false,
      },
      {
        id: "267c628",
        tags: ["main", "origin/main"],
        parent: "abc1234",
        cx: 140,
        cy: 437,
        branchless: false,
      },
      {
        id: "94b5af7",
        tags: [],
        parent: "abc1234",
        cx: 140,
        cy: 347,
        branchless: false,
      },
      {
        id: "4aca73f",
        tags: ["feature", "origin/feature", "HEAD"],
        parent: "94b5af7",
        cx: 230,
        cy: 347,
        branchless: false,
      },
    ],
    originData: [
      {
        id: "abc1234",
        tags: [],
        message: "first commit",
        parent: "initial",
        cx: 50,
        cy: 360,
        branchless: false,
      },
      {
        id: "267c628",
        tags: ["main"],
        parent: "abc1234",
        cx: 140,
        cy: 360,
        branchless: false,
      },
      {
        id: "4aca73f",
        tags: [],
        parent: "94b5af7",
        cx: 230,
        cy: 270,
        branchless: true,
      },
      {
        id: "94b5af7",
        tags: [],
        parent: "abc1234",
        cx: 140,
        cy: 270,
        branchless: false,
      },
      {
        id: "0c5bda6",
        tags: ["feature", "HEAD"],
        message: "force push",
        parent: "94b5af7",
        cx: 230,
        cy: 180,
        branchless: false,
      },
    ],
  };

  var fetchPullPush = {
    title: "Fetch Pull Push",
    key: "fetch-pull-push",
    message:
      "Fetch / pull data from the remote (origin) and push data to the remote.",
    commitData: [
      {
        id: "abc1234",
        tags: [],
        message: "first commit",
        parent: "initial",
        cx: 50,
        cy: 437,
        branchless: false,
      },
      {
        id: "2c85fc6",
        tags: ["main", "HEAD", "origin/main"],
        parent: "abc1234",
        cx: 140,
        cy: 437,
        branchless: false,
      },
    ],
    currentBranch: "main",
    originData: [
      {
        id: "abc1234",
        tags: [],
        message: "first commit",
        parent: "initial",
        cx: 50,
        cy: 360,
        branchless: false,
      },
      {
        id: "2c85fc6",
        tags: [],
        parent: "abc1234",
        cx: 140,
        cy: 360,
        branchless: false,
      },
      {
        id: "4d791cb",
        tags: [],
        parent: "2c85fc6",
        cx: 230,
        cy: 360,
        branchless: false,
      },
      {
        id: "aa50ff9",
        tags: ["main", "HEAD"],
        parent: "4d791cb",
        cx: 320,
        cy: 360,
        branchless: false,
      },
    ],
  };

  var pullRebase = {
    title: "Pull --rebase",
    key: "pull-rebase",
    message:
      "You committed locally after an update was pushed to the remote. What happens if you try and pull?",
    commitData: [
      {
        id: "abc1234",
        tags: [],
        message: "first commit",
        parent: "initial",
        cx: 50,
        cy: 437,
        branchless: false,
      },
      {
        id: "1ee0de4",
        tags: ["origin/main"],
        parent: "abc1234",
        cx: 140,
        cy: 437,
        branchless: false,
      },
      {
        id: "3a77c0d",
        tags: ["main", "HEAD"],
        message: "matt's change",
        parent: "1ee0de4",
        cx: 230,
        cy: 437,
        branchless: false,
      },
    ],
    currentBranch: "main",
    originData: [
      {
        id: "abc1234",
        tags: [],
        message: "first commit",
        parent: "initial",
        cx: 50,
        cy: 360,
        branchless: false,
      },
      {
        id: "1ee0de4",
        tags: [],
        parent: "abc1234",
        cx: 140,
        cy: 360,
        branchless: false,
      },
      {
        id: "b177c0d",
        tags: ["main", "HEAD"],
        message: "bill's change",
        parent: "1ee0de4",
        cx: 230,
        cy: 360,
        branchless: false,
      },
    ],
  };

  var resetExample = {
    title: "Reset Example",
    key: "reset",
    message: "Try resetting `main` to various other commits",
    currentBranch: "main",
    commitData: [
      {
        id: "abc1234",
        tags: [],
        message: "first commit",
        parent: "initial",
        cx: 50,
        cy: 437,
        branchless: false,
      },
      {
        id: "1111111",
        tags: [],
        parent: "abc1234",
        cx: 140,
        cy: 437,
        branchless: false,
      },
      {
        id: "2222222",
        tags: [],
        parent: "1111111",
        cx: 230,
        cy: 347,
        branchless: false,
        isNoFFBranch: true,
      },
      {
        id: "3333333",
        tags: [],
        parent: "2222222",
        cx: 320,
        cy: 347,
        branchless: false,
      },
      {
        id: "4444444",
        tags: [],
        parent: "abc1234",
        cx: 140,
        cy: 527,
        branchless: false,
        isNoFFBranch: true,
      },
      {
        id: "5555555",
        tags: [],
        parent: "4444444",
        cx: 230,
        cy: 527,
        branchless: false,
      },
      {
        id: "6666666",
        tags: [],
        parent: "5555555",
        cx: 320,
        cy: 527,
        branchless: false,
      },
      {
        parent2: "3333333",
        isNoFFCommit: true,
        id: "7777777",
        tags: [],
        message: "Merge",
        parent: "1111111",
        cx: 410,
        cy: 437,
        branchless: false,
      },
      {
        parent2: "6666666",
        isNoFFCommit: true,
        id: "8888888",
        tags: [],
        message: "Merge",
        parent: "7777777",
        cx: 500,
        cy: 437,
        branchless: false,
      },
      {
        id: "9999999",
        tags: ["main", "HEAD"],
        parent: "8888888",
        cx: 590,
        cy: 437,
        branchless: false,
      },
    ],
  };

  var cherryPick = {
    title: "Cherry-pick",
    key: "cherry-pick",
    message: "",
    commitData: [
      {
        id: "abc1234",
        tags: [],
        message: "first commit",
        parent: "initial",
        cx: 50,
        cy: 437,
        branchless: false,
      },
      {
        id: "d78de96",
        tags: ["main"],
        parent: "abc1234",
        cx: 140,
        cy: 437,
        branchless: false,
      },
      {
        id: "78d22fb",
        tags: [],
        parent: "d78de96",
        cx: 230,
        cy: 437,
        branchless: false,
      },
      {
        id: "239b2b1",
        tags: ["my-feature", "HEAD"],
        parent: "78d22fb",
        cx: 320,
        cy: 437,
        branchless: false,
      },
      {
        id: "73b3905",
        tags: [],
        message: "don't need 1",
        parent: "d78de96",
        cx: 230,
        cy: 347,
        branchless: false,
      },
      {
        id: "da7a000",
        tags: [],
        message: "do need",
        parent: "73b3905",
        cx: 320,
        cy: 347,
        branchless: false,
      },
      {
        id: "0025f2a",
        tags: ["other-feature"],
        message: "don't need 2",
        parent: "da7a000",
        cx: 410,
        cy: 347,
        branchless: false,
      },
    ],
    currentBranch: "my-feature",
  };

  var rebaseExample = {
    title: "Rebase Example",
    key: "rebase-example",
    message: "Try rebasing the `feature` branch onto `main`",
    commitData: [
      {
        id: "abc1234",
        tags: [],
        message: "first commit",
        parent: "initial",
        cx: 50,
        cy: 437,
        branchless: false,
      },
      {
        id: "4c7f2da",
        tags: [],
        parent: "abc1234",
        cx: 140,
        cy: 437,
        branchless: false,
      },
      {
        id: "1fbf33c",
        tags: ["main"],
        message: "important hotfix",
        parent: "4c7f2da",
        cx: 230,
        cy: 437,
        branchless: false,
      },
      {
        id: "44631d2",
        tags: [],
        parent: "4c7f2da",
        cx: 230,
        cy: 347,
        branchless: false,
      },
      {
        id: "9431439",
        tags: [],
        parent: "44631d2",
        cx: 320,
        cy: 347,
        branchless: false,
      },
      {
        id: "683a437",
        tags: ["feature", "HEAD"],
        parent: "9431439",
        cx: 410,
        cy: 347,
        branchless: false,
      },
    ],
    currentBranch: "feature",
  };

  var revertExample = {
    title: "Revert Example",
    key: "revert",
    message: "Oops, commit `badc0de` introduced a bug. Quickly revert it to undo those specific changes.",
    commitData: [
      {
        id: "abc1234",
        tags: [],
        message: "first commit",
        parent: "initial",
        cx: 50,
        cy: 437,
        branchless: false,
      },
      {
        id: "b239aea",
        tags: [],
        parent: "abc1234",
        cx: 140,
        cy: 437,
        branchless: false,
      },
      {
        id: "3306984",
        tags: [],
        parent: "b239aea",
        cx: 230,
        cy: 437,
        branchless: false,
      },
      {
        id: "badc0de",
        tags: [],
        message: "oops a bug",
        parent: "3306984",
        cx: 320,
        cy: 437,
        branchless: false,
      },
      {
        id: "5492ffc",
        tags: [],
        parent: "badc0de",
        cx: 410,
        cy: 437,
        branchless: false,
      },
      {
        id: "cd3d263",
        tags: ["main", "HEAD"],
        parent: "5492ffc",
        cx: 500,
        cy: 437,
        branchless: false,
      },
    ],
    currentBranch: "main",
  };

  return [
    free,
    freeWithRemote,
    mergeExample,
    fetchPullPush,
    resetExample,
    rebaseExample,
    pullRebase,
    rewrittenHistory,
    cherryPick,
    revertExample,
  ];
});
