define([], function () {
  var free = {
    title: "Free Explore",
    key: "free",
    message: "Test out 'commit', 'branch', and 'checkout'",
    commitData: [{ id: "abc1234", tags: ["main"], message: "first commit" }],
  };

  var freeWithRemote = {
    title: "Free Explore with Remote",
    key: "free-remote",
    message: "Have fun!",
    commitData: [
      { id: "abc1234", tags: ["main", "origin/main"], message: "first commit" },
    ],
    originData: [{ id: "abc1234", tags: ["main"], message: "first commit" }],
  };

  var mergeExample = {
    title: "Merge Example",
    key: "merge-example",
    commitData: [
      {
        id: "abc1234",
        tags: [],
        message: "first commit",
        parent: "initial",
        cx: 50,
        cy: 369,
        branchless: false,
      },
      {
        id: "818b21c",
        tags: ["main", "HEAD"],
        parent: "abc1234",
        cx: 140,
        cy: 369,
        branchless: false,
      },
      {
        id: "5fb6bcc",
        tags: [],
        parent: "818b21c",
        cx: 230,
        cy: 369,
        branchless: false,
      },
      {
        id: "dcfc607",
        tags: ["feature-1"],
        parent: "5fb6bcc",
        cx: 320,
        cy: 369,
        branchless: false,
      },
      {
        id: "15ec1bd",
        tags: [],
        parent: "abc1234",
        cx: 140,
        cy: 279,
        branchless: false,
      },
      {
        id: "0f2baaf",
        tags: [],
        parent: "15ec1bd",
        cx: 230,
        cy: 279,
        branchless: false,
      },
      {
        id: "b1ecc95",
        tags: ["feature-2"],
        parent: "0f2baaf",
        cx: 320,
        cy: 279,
        branchless: false,
      },
    ],
    currentBranch: "main",
  };

  var upstreamChanges = {
    title: "Upstream Changes",
    key: "upstream-changes",
    message: "Someone else has been working here!",
    currentBranch: "feature",
    commitData: [
      {
        id: "abc1234",
        tags: [],
        message: "first commit",
        parent: "initial",
      },
      {
        id: "84c98fe",
        parent: "abc1234",
        tags: ["main", "origin/main"],
      },
      {
        id: "1c016b6",
        parent: "abc1234",
        tags: ["feature", "origin/feature", "HEAD"],
      },
    ],
    originData: [
      {
        id: "abc1234",
        tags: [],
        message: "first commit",
        parent: "initial",
      },
      {
        id: "84c98fe",
        parent: "abc1234",
        tags: ["main", "HEAD"],
      },
      {
        id: "1c016b6",
        parent: "abc1234",
        tags: [],
      },
      {
        id: "fd0af32",
        tags: ["feature"],
        parent: "1c016b6",
      },
    ],
  };

  var rewrittenHistory = {
    title: "Rewritten Remote History",
    key: "rewritten-history",
    message: "Someone force-pushed and re-wrote history on the remote!",
    currentBranch: "feature",
    commitData: [
      {
        id: "abc1234",
        tags: [],
        message: "first commit",
        parent: "initial",
        cx: 50,
        cy: 437,
        branchless: false,
      },
      {
        id: "267c628",
        tags: ["main", "origin/main"],
        parent: "abc1234",
        cx: 140,
        cy: 437,
        branchless: false,
      },
      {
        id: "94b5af7",
        tags: [],
        parent: "abc1234",
        cx: 140,
        cy: 347,
        branchless: false,
      },
      {
        id: "4aca73f",
        tags: ["feature", "origin/feature", "HEAD"],
        parent: "94b5af7",
        cx: 230,
        cy: 347,
        branchless: false,
      },
    ],
    originData: [
      {
        id: "abc1234",
        tags: [],
        message: "first commit",
        parent: "initial",
        cx: 50,
        cy: 360,
        branchless: false,
      },
      {
        id: "267c628",
        tags: ["main"],
        parent: "abc1234",
        cx: 140,
        cy: 360,
        branchless: false,
      },
      {
        id: "4aca73f",
        tags: [],
        parent: "94b5af7",
        cx: 230,
        cy: 270,
        branchless: true,
      },
      {
        id: "94b5af7",
        tags: [],
        parent: "abc1234",
        cx: 140,
        cy: 270,
        branchless: false,
      },
      {
        id: "0c5bda6",
        tags: ["feature", "HEAD"],
        message: "force push",
        parent: "94b5af7",
        cx: 230,
        cy: 180,
        branchless: false,
      },
    ],
  };

  var revert = {
    title: "Revert",
    key: "revert",
    message: "Oops, let's revert some commits",
    commitData: [
      {
        id: "abc1234",
        tags: [],
        message: "first commit",
        parent: "initial",
        cx: 50,
        cy: 330,
        branchless: false,
      },
      {
        id: "dd70cfe",
        tags: [],
        parent: "abc1234",
        cx: 140,
        cy: 330,
        branchless: false,
      },
      {
        id: "2545b6f",
        tags: [],
        parent: "dd70cfe",
        cx: 230,
        cy: 330,
        branchless: false,
      },
      {
        id: "3d6ef16",
        tags: [],
        parent: "dd70cfe",
        cx: 230,
        cy: 240,
        branchless: false,
      },
      {
        id: "077415f",
        tags: ["feature"],
        parent: "3d6ef16",
        cx: 320,
        cy: 240,
        branchless: false,
      },
      {
        parent2: "077415f",
        id: "8686fb6",
        tags: ["main", "HEAD"],
        message: "Merge",
        parent: "2545b6f",
        cx: 410,
        cy: 330,
        branchless: false,
      },
    ],
  };

  var cherryPick = {
    title: "Cherry Pick",
    key: "cherry-pick",
    message: "Let's pick some commits",
    commitData: [
      {
        id: "abc1234",
        tags: [],
        message: "first commit",
        parent: "initial",
        cx: 50,
        cy: 318,
        branchless: false,
      },
      {
        id: "790dd94",
        tags: [],
        parent: "abc1234",
        cx: 140,
        cy: 318,
        branchless: false,
      },
      {
        id: "96e9ce7",
        tags: ["[bugfix1]"],
        parent: "790dd94",
        cx: 230,
        cy: 318,
        branchless: false,
      },
      {
        id: "44db644",
        tags: [],
        parent: "96e9ce7",
        cx: 320,
        cy: 318,
        branchless: false,
      },
      {
        id: "06127d7",
        tags: [],
        parent: "44db644",
        cx: 410,
        cy: 318,
        branchless: false,
      },
      {
        id: "60c6c2c",
        tags: [],
        parent: "790dd94",
        cx: 230,
        cy: 228,
        branchless: false,
      },
      {
        id: "8f7c801",
        tags: ["release", "HEAD"],
        parent: "60c6c2c",
        cx: 320,
        cy: 228,
        branchless: false,
      },
      {
        id: "78ecb32",
        tags: [],
        parent: "44db644",
        cx: 410,
        cy: 228,
        branchless: false,
      },
      {
        id: "12e9bbb",
        tags: ["bugfix2"],
        parent: "78ecb32",
        cx: 500,
        cy: 228,
        branchless: false,
      },
      {
        id: "e8ce346",
        tags: [],
        parent: "06127d7",
        cx: 500,
        cy: 318,
        branchless: false,
      },
      {
        parent2: "12e9bbb",
        id: "5749661",
        tags: ["main"],
        message: "Merge",
        parent: "e8ce346",
        cx: 590,
        cy: 318,
        branchless: false,
      },
    ],
  };

  return [
    free,
    freeWithRemote,
    mergeExample,
    upstreamChanges,
    rewrittenHistory,
    revert,
    cherryPick,
  ];
});
